<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Influencer extends Model
{
    public const TYPE_PERCENT = 'percent';
    public const TYPE_FLAT = 'flat';

    protected $fillable = [
        'user_id',
        'coupon_id',
        'name',
        'phone',
        'instagram_handle',
        'commission_type',
        'commission_value',
        'upi_id',
        'bank_details',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'commission_value' => 'decimal:2',
            'bank_details' => 'array',
            'is_active' => 'boolean',
        ];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function coupon(): BelongsTo
    {
        return $this->belongsTo(Coupon::class);
    }

    public function commissions(): HasMany
    {
        return $this->hasMany(InfluencerCommission::class);
    }

    /**
     * Total Gross Sales (Subtotal) generated by this influencer.
     */
    public function getTotalSalesAttribute(): float
    {
        return (float) $this->commissions()
            ->whereNotIn('status', ['cancelled'])
            ->sum('order_subtotal');
    }

    /**
     * Total Lifetime Commission Earned.
     */
    public function getTotalEarnedAttribute(): float
    {
        return (float) $this->commissions()
            ->whereNotIn('status', ['cancelled'])
            ->sum('commission_amount');
    }

    /**
     * Pending & Approved (Unpaid) Commission Balance.
     */
    public function getPendingPayoutAttribute(): float
    {
        return (float) $this->commissions()
            ->whereIn('status', ['pending', 'approved'])
            ->sum('commission_amount');
    }

    /**
     * Total Paid Commission.
     */
    public function getPaidEarningsAttribute(): float
    {
        return (float) $this->commissions()
            ->where('status', 'paid')
            ->sum('commission_amount');
    }

    /**
     * Count of successful referral orders.
     */
    public function getTotalOrdersCountAttribute(): int
    {
        return $this->commissions()
            ->whereNotIn('status', ['cancelled'])
            ->count();
    }
}
